In [119]:
# ============================================
# 1. IMPORTATION DES BIBLIOTHÈQUES
# ============================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
import sys

In [120]:
# ============================================
# 2. CONFIGURATION DU CHEMIN DU PROJET
# ============================================

ROOT_DIR = Path.cwd().parent

if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

print("Racine du projet :", ROOT_DIR)

Racine du projet : c:\Users\Olaya\Desktop\sprint_1\SmartHouse_Predictor

In [121]:
# ============================================
# 3. CHARGEMENT DU DATASET
# ============================================

from src.data_preparation import load_data, basic_information

df = load_data()

print("Dataset chargé avec succès !")

Dataset chargé avec succès !

In [122]:
# ============================================
# 4. DIMENSIONS DU DATASET
# ============================================

print("Nombre de lignes :", df.shape[0])
print("Nombre de colonnes :", df.shape[1])

Nombre de lignes : 2919
Nombre de colonnes : 81

In [123]:
# ============================================
# 5. APERÇU DES DONNÉES
# ============================================

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [124]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,167081.220949
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,164788.778231
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,219222.423400
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,184924.279659
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,187741.866657

In [125]:
df.sample(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
515,516,20,RL,94.0,12220,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,New,Partial,402861.000000
265,266,20,RL,78.0,12090,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2008,WD,Normal,175500.000000
2337,2338,20,RL,91.0,11830,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2007,New,Partial,186760.207966
1542,1543,75,RL,NaN,7793,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,173912.421165
902,903,60,RL,63.0,7875,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,180000.000000

In [126]:
# ============================================
# 6. INFORMATIONS SUR LES VARIABLES
# ============================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   str
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   str
 6   Alley          198 non-null    str
 7   LotShape       2919 non-null   str
 8   LandContour    2919 non-null   str
 9   Utilities      2917 non-null   str
 10  LotConfig      2919 non-null   str
 11  LandSlope      2919 non-null   str
 12  Neighborhood   2919 non-null   str
 13  Condition1     2919 non-null   str
 14  Condition2     2919 non-null   str
 15  BldgType       2919 non-null   str
 16  HouseStyle     2919 non-null   str
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   str
 22  RoofMatl       2919 non-null   str
 23  Exterior1st    2918 non-null   str
 24  Exterior2nd    2918 non-null   str
 25  MasVnrType     1153 non-null   str
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   str
 28  ExterCond      2919 non-null   str
 29  Foundation     2919 non-null   str
 30  BsmtQual       2838 non-null   str
 31  BsmtCond       2837 non-null   str
 32  BsmtExposure   2837 non-null   str
 33  BsmtFinType1   2840 non-null   str
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   str
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   str
 40  HeatingQC      2919 non-null   str
 41  CentralAir     2919 non-null   str
 42  Electrical     2918 non-null   str
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   str
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   str
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   str
 58  GarageType     2762 non-null   str
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   str
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   str
 64  GarageCond     2760 non-null   str
 65  PavedDrive     2919 non-null   str
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     str
 73  Fence          571 non-null    str
 74  MiscFeature    105 non-null    str
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   str
 79  SaleCondition  2919 non-null   str
 80  SalePrice      2919 non-null   float64
dtypes: float64(12), int64(26), str(43)
memory usage: 2.2 MB

In [127]:
# ============================================
# 7. TYPES DE VARIABLES
# ============================================

print("Variables numériques :")
print(df.select_dtypes(include=np.number).columns.tolist())

print("\nVariables catégorielles :")
print(df.select_dtypes(include="object").columns.tolist())

Variables numériques :
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

Variables catégorielles :
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

C:\Users\Olaya\AppData\Local\Temp\ipykernel_10732\3871714707.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns.tolist())

In [128]:
# ============================================
# 7. TYPES DE VARIABLES
# ============================================

print("Variables numériques :")
print(df.select_dtypes(include=np.number).columns.tolist())

print("\nVariables catégorielles :")
print(df.select_dtypes(include="object").columns.tolist())

Variables numériques :
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

Variables catégorielles :
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

C:\Users\Olaya\AppData\Local\Temp\ipykernel_10732\3871714707.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns.tolist())

In [129]:
# ============================================
# 8. STATISTIQUES DES VARIABLES NUMÉRIQUES
# ============================================

df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180052.854647
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,57381.565721
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,154795.084126
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,176734.841494
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,191895.744157
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [130]:
print("Statistiques de SalePrice :")
print(df["SalePrice"].describe())

Statistiques de SalePrice :
count      2919.000000
mean     180052.854647
std       57381.565721
min       34900.000000
25%      154795.084126
50%      176734.841494
75%      191895.744157
max      755000.000000
Name: SalePrice, dtype: float64

In [131]:
# ============================================
# 9. RECHERCHE DES DOUBLONS
# ============================================

duplicate_count = df.duplicated().sum()

print("Nombre de lignes dupliquées :", duplicate_count)

Nombre de lignes dupliquées : 0

In [132]:
# ============================================
# 10. VÉRIFICATION DE L'IDENTIFIANT
# ============================================

print("Nombre total de lignes :", len(df))
print("Nombre d'IDs différents :", df["Id"].nunique())

Nombre total de lignes : 2919
Nombre d'IDs différents : 2919

In [133]:
print("Nombre d'IDs dupliqués :", df["Id"].duplicated().sum())

Nombre d'IDs dupliqués : 0

In [134]:
# ============================================
# 11. ANALYSE DES VALEURS MANQUANTES
# ============================================

missing = df.isna().sum().to_frame("missing_count")

missing["missing_percent"] = (
    missing["missing_count"] / len(df) * 100
)

missing = (
    missing[missing["missing_count"] > 0]
    .sort_values("missing_percent", ascending=False)
)

missing

              missing_count  missing_percent
PoolQC                 2909        99.657417
MiscFeature            2814        96.402878
Alley                  2721        93.216855
Fence                  2348        80.438506
MasVnrType             1766        60.500171
FireplaceQu            1420        48.646797
LotFrontage             486        16.649538
GarageQual              159         5.447071
GarageYrBlt             159         5.447071
GarageCond              159         5.447071
GarageFinish            159         5.447071
GarageType              157         5.378554
BsmtExposure             82         2.809181
BsmtCond                 82         2.809181
BsmtQual                 81         2.774923
BsmtFinType2             80         2.740665
BsmtFinType1             79         2.706406
MasVnrArea               23         0.787941
MSZoning                  4         0.137033
BsmtFullBath              2         0.068517
Functional                2         0.068517
BsmtHalfBath              2         0.068517
Utilities                 2         0.068517
BsmtFinSF1                1         0.034258
Exterior2nd               1         0.034258
Exterior1st               1         0.034258
Electrical                1         0.034258
TotalBsmtSF               1         0.034258
BsmtUnfSF                 1         0.034258
BsmtFinSF2                1         0.034258
KitchenQual               1         0.034258
GarageArea                1         0.034258
GarageCars                1         0.034258
SaleType                  1         0.034258

In [135]:
# ============================================
# 12. TOP DES VARIABLES AVEC DES VALEURS MANQUANTES
# ============================================

plt.figure(figsize=(12, 6))

sns.barplot(
    x=missing["missing_percent"].head(15),
    y=missing.head(15).index
)

plt.title("Top 15 des variables avec des valeurs manquantes")
plt.xlabel("Pourcentage de valeurs manquantes (%)")
plt.ylabel("Variable")

# Sauvegarder le graphique
plt.savefig("../data/missing_values.png", bbox_inches="tight")

# Pas besoin de plt.show() ici
plt.close()

In [136]:
df = df.fillna(0)

In [137]:
# ============================================
# 13. ANALYSE DE POOLQC
# ============================================

print(df["PoolQC"].value_counts(dropna=False))

PoolQC
0     2909
Ex       4
Gd       4
Fa       2
Name: count, dtype: int64

In [138]:
# ============================================
# ANALYSE DE L'ACCÈS PAR RUELLE
# ============================================

print(df["Alley"].value_counts(dropna=False))

Alley
0       2721
Grvl     120
Pave      78
Name: count, dtype: int64

In [139]:
# ============================================
# ANALYSE DE LA CLÔTURE
# ============================================

print(df["Fence"].value_counts(dropna=False))

Fence
0        2348
MnPrv     329
GdPrv     118
GdWo      112
MnWw       12
Name: count, dtype: int64

In [140]:
# ============================================
# ANALYSE DES CHEMINÉES
# ============================================

print(df["FireplaceQu"].value_counts(dropna=False))

FireplaceQu
0     1420
Gd     744
TA     592
Fa      74
Po      46
Ex      43
Name: count, dtype: int64

In [141]:
# ============================================
# ANALYSE DES VARIABLES DU GARAGE
# ============================================

garage_columns = [
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "GarageYrBlt",
    "GarageCars",
    "GarageArea"
]

for col in garage_columns:
    print(f"\n========== {col} ==========")
    print(df[col].value_counts(dropna=False).head(15))

========== GarageType ==========
GarageType
Attchd     1723
Detchd      779
BuiltIn     186
0           157
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64

========== GarageFinish ==========
GarageFinish
Unf    1230
RFn     811
Fin     719
0       159
Name: count, dtype: int64

========== GarageQual ==========
GarageQual
TA    2604
0      159
Fa     124
Gd      24
Po       5
Ex       3
Name: count, dtype: int64

========== GarageCond ==========
GarageCond
TA    2654
0      159
Fa      74
Gd      15
Po      14
Ex       3
Name: count, dtype: int64

========== GarageYrBlt ==========
GarageYrBlt
0.0       159
2005.0    142
2006.0    115
2007.0    115
2004.0     99
2003.0     92
1977.0     66
2008.0     61
1998.0     58
2000.0     55
1999.0     54
2002.0     53
1950.0     51
1976.0     50
1993.0     49
Name: count, dtype: int64

========== GarageCars ==========
GarageCars
2.0    1594
1.0     776
3.0     374
0.0     158
4.0      16
5.0       1
Name: count, dtype: int64

========== GarageArea ==========
GarageArea
0.0      158
576.0     97
440.0     96
240.0     69
484.0     68
528.0     65
400.0     58
480.0     54
264.0     51
288.0     50
308.0     48
280.0     30
420.0     29
336.0     29
672.0     23
Name: count, dtype: int64

In [142]:
# ============================================
# ANALYSE DES VARIABLES DU SOUS-SOL
# ============================================

bsmt_columns = [
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "BsmtFullBath",
    "BsmtHalfBath"
]

for col in bsmt_columns:
    print(f"\n========== {col} ==========")
    print(df[col].value_counts(dropna=False).head(15))

========== BsmtQual ==========
BsmtQual
TA    1283
Gd    1209
Ex     258
Fa      88
0       81
Name: count, dtype: int64

========== BsmtCond ==========
BsmtCond
TA    2606
Gd     122
Fa     104
0       82
Po       5
Name: count, dtype: int64

========== BsmtExposure ==========
BsmtExposure
No    1904
Av     418
Gd     276
Mn     239
0       82
Name: count, dtype: int64

========== BsmtFinType1 ==========
BsmtFinType1
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
0       79
Name: count, dtype: int64

========== BsmtFinType2 ==========
BsmtFinType2
Unf    2493
Rec     105
LwQ      87
0        80
BLQ      68
ALQ      52
GLQ      34
Name: count, dtype: int64

========== BsmtFinSF1 ==========
BsmtFinSF1
0.0      930
24.0      27
16.0      14
300.0      9
384.0      8
600.0      8
288.0      8
20.0       8
456.0      7
360.0      7
700.0      7
624.0      7
500.0      7
375.0      7
936.0      7
Name: count, dtype: int64

========== BsmtFinSF2 ==========
BsmtFinSF2
0.0      2572
180.0       5
294.0       5
374.0       3
147.0       3
539.0       3
435.0       3
168.0       3
144.0       3
162.0       3
483.0       3
93.0        2
712.0       2
41.0        2
670.0       2
Name: count, dtype: int64

========== BsmtUnfSF ==========
BsmtUnfSF
0.0      242
384.0     19
728.0     14
672.0     13
600.0     12
216.0     11
816.0     11
572.0     11
100.0     11
270.0     10
624.0     10
300.0     10
280.0      9
396.0      9
186.0      9
Name: count, dtype: int64

========== TotalBsmtSF ==========
TotalBsmtSF
0.0       79
864.0     74
672.0     29
912.0     26
1040.0    25
768.0     24
816.0     23
728.0     20
384.0     19
780.0     19
1008.0    19
960.0     18
756.0     17
832.0     17
894.0     17
Name: count, dtype: int64

========== BsmtFullBath ==========
BsmtFullBath
0.0    1707
1.0    1172
2.0      38
3.0       2
Name: count, dtype: int64

========== BsmtHalfBath ==========
BsmtHalfBath
0.0    2744
1.0     171
2.0       4
Name: count, dtype: int64

In [143]:
# ============================================
# ANALYSE DU MASONRY VENEER
# ============================================

print("========== MasVnrType ==========")
print(df["MasVnrType"].value_counts(dropna=False))

print("\n========== MasVnrArea ==========")
print(df["MasVnrArea"].describe())

========== MasVnrType ==========
MasVnrType
0          1766
BrkFace     879
Stone       249
BrkCmn       25
Name: count, dtype: int64

========== MasVnrArea ==========
count    2919.000000
mean      101.396026
std       178.854579
min         0.000000
25%         0.000000
50%         0.000000
75%       163.500000
max      1600.000000
Name: MasVnrArea, dtype: float64

In [144]:
# ============================================
# VARIABLES AVEC PEU DE VALEURS MANQUANTES
# ============================================

missing_small = missing[
    missing["missing_percent"] < 1
]

missing_small

              missing_count  missing_percent
MasVnrArea               23         0.787941
MSZoning                  4         0.137033
BsmtFullBath              2         0.068517
Functional                2         0.068517
BsmtHalfBath              2         0.068517
Utilities                 2         0.068517
BsmtFinSF1                1         0.034258
Exterior2nd               1         0.034258
Exterior1st               1         0.034258
Electrical                1         0.034258
TotalBsmtSF               1         0.034258
BsmtUnfSF                 1         0.034258
BsmtFinSF2                1         0.034258
KitchenQual               1         0.034258
GarageArea                1         0.034258
GarageCars                1         0.034258
SaleType                  1         0.034258

In [145]:
# ============================================
# 13. DISTRIBUTION DE SALEPRICE
# ============================================

plt.figure(figsize=(10, 6))

sns.histplot(
    df["SalePrice"],
    kde=True
)

plt.title("Distribution du prix des logements")
plt.xlabel("SalePrice")
plt.ylabel("Nombre de logements")

# Sauvegarde du graphique
plt.savefig(
    "../data/saleprice_distribution.svg",
    format="svg",
    bbox_inches="tight"
)

plt.close()

print("Graphique sauvegardé avec succès.")

Graphique sauvegardé avec succès.

In [146]:
# ============================================
# 14. DÉTECTION DES VALEURS EXTRÊMES
# ============================================

# On utilise ici les quartiles pour repérer les valeurs
# qui peuvent être considérées comme extrêmes.

Q1 = df["SalePrice"].quantile(0.25)
Q3 = df["SalePrice"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["SalePrice"] < lower_bound) |
    (df["SalePrice"] > upper_bound)
]

print("Q1 :", Q1)
print("Q3 :", Q3)
print("IQR :", IQR)

print("\nLimite inférieure :", lower_bound)
print("Limite supérieure :", upper_bound)

print("\nNombre de valeurs extrêmes :", len(outliers))

Q1 : 154795.0841256345
Q3 : 191895.74415661948
IQR : 37100.66003098499

Limite inférieure : 99144.094079157
Limite supérieure : 247546.73420309694

Nombre de valeurs extrêmes : 348

In [147]:
# ============================================
# LISTE DES VARIABLES POUR LA PRÉPARATION
# ============================================

numeric_features = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = df.select_dtypes(
    include=["object"]
).columns.tolist()

print("Nombre de variables numériques :", len(numeric_features))
print("Nombre de variables catégorielles :", len(categorical_features))

Nombre de variables numériques : 38
Nombre de variables catégorielles : 43

C:\Users\Olaya\AppData\Local\Temp\ipykernel_10732\1269193435.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(

In [148]:
# Id ne doit pas être utilisé comme feature
if "Id" in numeric_features:
    numeric_features.remove("Id")

print("\nVariables numériques utilisées :", len(numeric_features))
print("Variables catégorielles :", len(categorical_features))

Variables numériques utilisées : 37
Variables catégorielles : 43

In [149]:
# ============================================
# SÉPARATION DES FEATURES ET DE LA TARGET
# ============================================

X = df.drop(
    columns=["SalePrice", "Id"]
)

y = df["SalePrice"]

print("Shape de X :", X.shape)
print("Shape de y :", y.shape)

Shape de X : (2919, 79)
Shape de y : (2919,)

In [150]:
# ============================================
# VÉRIFICATION AVANT LE NETTOYAGE
# ============================================

print("X :", X.shape)
print("y :", y.shape)

print("\nValeurs manquantes dans X :", X.isna().sum().sum())
print("Valeurs manquantes dans y :", y.isna().sum())

X : (2919, 79)
y : (2919,)

Valeurs manquantes dans X : 0
Valeurs manquantes dans y : 0

In [151]:
# ============================================
# 15. CRÉATION D'UNE COPIE POUR LE NETTOYAGE
# ============================================

clean_df = df.copy()

print("Dataset original :", df.shape)
print("Dataset à nettoyer :", clean_df.shape)

Dataset original : (2919, 81)
Dataset à nettoyer : (2919, 81)

In [152]:
# ============================================
# 16. VALEURS MANQUANTES AVANT NETTOYAGE
# ============================================

missing_before = clean_df.isna().sum()

missing_before = (
    missing_before[missing_before > 0]
    .sort_values(ascending=False)
)

print("Nombre de colonnes avec des valeurs manquantes :",
      len(missing_before))

missing_before

Nombre de colonnes avec des valeurs manquantes : 0

Series([], dtype: int64)

In [153]:
# ============================================
# VÉRIFICATION APRÈS NETTOYAGE
# ============================================

missing_after = clean_df.isna().sum()

missing_after = (
    missing_after[missing_after > 0]
    .sort_values(ascending=False)
)

print("Nombre de colonnes avec des valeurs manquantes :", len(missing_after))
print("Nombre total de valeurs manquantes :", missing_after.sum())

Nombre de colonnes avec des valeurs manquantes : 0
Nombre total de valeurs manquantes : 0

In [154]:
# ============================================
# 17. VARIABLES CATÉGORIELLES
#     où NaN = absence de caractéristique
# ============================================

none_columns = [
    "PoolQC",
    "MiscFeature",
    "Alley",
    "Fence",
    "MasVnrType",
    "FireplaceQu",

    # Garage
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",

    # Basement
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2"
]

for col in none_columns:
    clean_df[col] = clean_df[col].fillna("None")

print("Colonnes traitées :", len(none_columns))

Colonnes traitées : 15

In [155]:
# ============================================
# 18. VARIABLES NUMÉRIQUES
#     où NaN correspond à une absence
# ============================================

zero_columns = [
    # Masonry
    "MasVnrArea",

    # Basement
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "BsmtFullBath",
    "BsmtHalfBath",

    # Garage
    "GarageCars",
    "GarageArea",
    "GarageYrBlt"
]

for col in zero_columns:
    clean_df[col] = clean_df[col].fillna(0)

print("Colonnes traitées :", len(zero_columns))

Colonnes traitées : 10

In [156]:
# ============================================
# 19. TRAITEMENT DE LOTFRONTAGE
# ============================================

clean_df["LotFrontage"] = (
    clean_df.groupby("Neighborhood")["LotFrontage"]
    .transform(lambda x: x.fillna(x.median()))
)

In [157]:
clean_df["LotFrontage"].fillna(
    clean_df["LotFrontage"].median()
)

0        65.0
1        80.0
2        68.0
3        60.0
4        84.0
        ...
2914     21.0
2915     21.0
2916    160.0
2917     62.0
2918     74.0
Name: LotFrontage, Length: 2919, dtype: float64

In [158]:
# ============================================
# 20. VARIABLES CATÉGORIELLES
#     AVEC TRÈS PEU DE VALEURS MANQUANTES
# ============================================

categorical_mode_columns = [
    "MSZoning",
    "Utilities",
    "Functional",
    "Exterior1st",
    "Exterior2nd",
    "Electrical",
    "KitchenQual",
    "SaleType"
]

for col in categorical_mode_columns:
    clean_df[col] = clean_df[col].fillna(
        clean_df[col].mode()[0]
    )

print("Colonnes traitées :", len(categorical_mode_columns))

Colonnes traitées : 8

In [159]:
clean_df[col].mode()[0]

'WD'

In [160]:
# ============================================
# 21. VÉRIFICATION APRÈS NETTOYAGE
# ============================================

missing_after = clean_df.isna().sum()

missing_after = (
    missing_after[missing_after > 0]
    .sort_values(ascending=False)
)

missing_after

Series([], dtype: int64)

In [161]:
# ============================================
# 22. CONTRÔLE FINAL DES VALEURS MANQUANTES
# ============================================

total_missing = clean_df.isna().sum()

print("Nombre total de valeurs manquantes :", total_missing)

Nombre total de valeurs manquantes : Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [162]:
# ============================================
# 23. VÉRIFICATION DE LA TAILLE DU DATASET
# ============================================

print("Avant nettoyage :", df.shape)
print("Après nettoyage :", clean_df.shape)

Avant nettoyage : (2919, 81)
Après nettoyage : (2919, 81)

In [163]:
# ============================================
# 24. VÉRIFICATION DES DOUBLONS
# ============================================

print(
    "Nombre de doublons après nettoyage :",
    clean_df.duplicated().sum()
)

Nombre de doublons après nettoyage : 0

In [164]:
# ============================================
# 25. CONTRÔLE DE QUELQUES VARIABLES
# ============================================

check_columns = [
    "PoolQC",
    "Alley",
    "Fence",
    "MasVnrType",
    "GarageType",
    "GarageCars",
    "BsmtQual",
    "TotalBsmtSF",
    "LotFrontage"
]

for col in check_columns:
    print(f"\n========== {col} ==========")
    print(clean_df[col].value_counts(dropna=False).head(10))

========== PoolQC ==========
PoolQC
0     2909
Ex       4
Gd       4
Fa       2
Name: count, dtype: int64

========== Alley ==========
Alley
0       2721
Grvl     120
Pave      78
Name: count, dtype: int64

========== Fence ==========
Fence
0        2348
MnPrv     329
GdPrv     118
GdWo      112
MnWw       12
Name: count, dtype: int64

========== MasVnrType ==========
MasVnrType
0          1766
BrkFace     879
Stone       249
BrkCmn       25
Name: count, dtype: int64

========== GarageType ==========
GarageType
Attchd     1723
Detchd      779
BuiltIn     186
0           157
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64

========== GarageCars ==========
GarageCars
2.0    1594
1.0     776
3.0     374
0.0     158
4.0      16
5.0       1
Name: count, dtype: int64

========== BsmtQual ==========
BsmtQual
TA    1283
Gd    1209
Ex     258
Fa      88
0       81
Name: count, dtype: int64

========== TotalBsmtSF ==========
TotalBsmtSF
0.0       79
864.0     74
672.0     29
912.0     26
1040.0    25
768.0     24
816.0     23
728.0     20
384.0     19
780.0     19
Name: count, dtype: int64

========== LotFrontage ==========
LotFrontage
0.0     486
60.0    276
80.0    137
70.0    133
50.0    117
75.0    105
65.0     93
85.0     76
21.0     50
24.0     49
Name: count, dtype: int64

In [165]:
#partie de preparation 

# ============================================
# TYPES DES VARIABLES
# ============================================

numeric_cols = clean_df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = clean_df.select_dtypes(include=["object"]).columns

print("Nombre de variables numériques :", len(numeric_cols))
print("Nombre de variables catégorielles :", len(categorical_cols))

print("\nVariables numériques :")
print(list(numeric_cols))

print("\nVariables catégorielles :")
print(list(categorical_cols))

Nombre de variables numériques : 38
Nombre de variables catégorielles : 43

Variables numériques :
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

Variables catégorielles :
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

C:\Users\Olaya\AppData\Local\Temp\ipykernel_10732\1150264777.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = clean_df.select_dtypes(include=["object"]).columns

In [166]:
categorical_cols = clean_df.select_dtypes(include=["str"]).columns

In [167]:
# ============================================
# SÉPARATION DES VARIABLES X ET y
# ============================================

# Variable cible
y = clean_df["SalePrice"]

# Variables explicatives
X = clean_df.drop(columns=["SalePrice", "Id"])

print("Dimensions de X :", X.shape)
print("Dimensions de y :", y.shape)

print("\nX contient SalePrice :", "SalePrice" in X.columns)
print("X contient Id :", "Id" in X.columns)

Dimensions de X : (2919, 79)
Dimensions de y : (2919,)

X contient SalePrice : False
X contient Id : False

In [168]:
# ============================================
# TRAIN / TEST SPLIT
# ============================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (2335, 79)
X_test  : (584, 79)
y_train : (2335,)
y_test  : (584,)

In [169]:
# ============================================
# ANALYSE DE SALEPRICE
# ============================================

print("=== Statistiques de SalePrice ===")
print(clean_df["SalePrice"].describe())

print("\n=== Médiane ===")
print(clean_df["SalePrice"].median())

print("\n=== Asymétrie (Skewness) ===")
print(clean_df["SalePrice"].skew())

=== Statistiques de SalePrice ===
count      2919.000000
mean     180052.854647
std       57381.565721
min       34900.000000
25%      154795.084126
50%      176734.841494
75%      191895.744157
max      755000.000000
Name: SalePrice, dtype: float64

=== Médiane ===
176734.841494027

=== Asymétrie (Skewness) ===
2.5492483896425098

In [170]:
print(clean_df.shape)

print(clean_df[["GrLivArea", "SalePrice"]].head())

print(clean_df[["GrLivArea", "SalePrice"]].isnull().sum())

(2919, 81)
   GrLivArea  SalePrice
0       1710   208500.0
1       1262   181500.0
2       1786   223500.0
3       1717   140000.0
4       2198   250000.0
GrLivArea    0
SalePrice    0
dtype: int64

In [171]:
print("GrLivArea" in clean_df.columns)
print("SalePrice" in clean_df.columns)

True
True

In [172]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.scatter(
    clean_df["GrLivArea"],
    clean_df["SalePrice"]
)

plt.title("Surface habitable vs prix de vente")
plt.xlabel("Surface habitable (GrLivArea)")
plt.ylabel("Prix de vente (SalePrice)")

plt.savefig("eda_surface_vs_prix.png", dpi=150, bbox_inches="tight")

plt.close()

In [173]:
# ============================================
# 26. QUALITÉ DU LOGEMENT VS PRIX
# ============================================

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=clean_df,
    x="OverallQual",
    y="SalePrice"
)

plt.title("Qualité du logement vs prix de vente")
plt.xlabel("Qualité globale du logement")
plt.ylabel("Prix de vente")

plt.savefig(
    "eda_qualite_vs_prix.png",
    dpi=150,
    bbox_inches="tight"
)

plt.close()

In [174]:
# ============================================
# 27. QUARTIER VS PRIX
# ============================================

plt.figure(figsize=(14, 7))

sns.boxplot(
    data=clean_df,
    x="Neighborhood",
    y="SalePrice"
)

plt.title("Prix de vente selon le quartier")
plt.xlabel("Quartier")
plt.ylabel("Prix de vente")

plt.xticks(rotation=45)

plt.tight_layout()

plt.savefig(
    "eda_neighborhood_vs_prix.png",
    dpi=150,
    bbox_inches="tight"
)

plt.close()

In [175]:
# ============================================
# 28. ANNÉE DE CONSTRUCTION VS PRIX
# ============================================

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=clean_df,
    x="YearBuilt",
    y="SalePrice"
)

plt.title("Année de construction vs prix de vente")
plt.xlabel("Année de construction")
plt.ylabel("Prix de vente")

plt.savefig(
    "eda_yearbuilt_vs_prix.png",
    dpi=150,
    bbox_inches="tight"
)

plt.close()

In [176]:
# ============================================
# 29. MATRICE DE CORRÉLATION
# ============================================

numeric_df = clean_df.select_dtypes(
    include=["int64", "float64"]
)

correlation = numeric_df.corr()

plt.figure(figsize=(16, 12))

sns.heatmap(
    correlation,
    cmap="coolwarm",
    center=0
)

plt.title("Matrice de corrélation des variables numériques")

plt.tight_layout()

plt.savefig(
    "eda_correlation_matrix.png",
    dpi=150,
    bbox_inches="tight"
)

plt.close()

In [177]:
# ============================================
# 30. VARIABLES LES PLUS CORRÉLÉES AVEC SALEPRICE
# ============================================

price_correlation = (
    correlation["SalePrice"]
    .sort_values(ascending=False)
)

print(price_correlation.head(15))

SalePrice       1.000000
GrLivArea       0.588010
OverallQual     0.550911
TotRmsAbvGrd    0.469800
GarageCars      0.468861
GarageArea      0.464467
1stFlrSF        0.462865
TotalBsmtSF     0.453089
FullBath        0.433710
YearBuilt       0.362066
Fireplaces      0.353567
MasVnrArea      0.351883
YearRemodAdd    0.350032
LotArea         0.296497
BsmtFinSF1      0.272281
Name: SalePrice, dtype: float64

In [178]:
print(price_correlation.tail(10))

MiscVal         -0.000037
BsmtFinSF2      -0.007398
Id              -0.011630
BsmtHalfBath    -0.012734
LowQualFinSF    -0.015395
YrSold          -0.039064
OverallCond     -0.065785
EnclosedPorch   -0.070698
KitchenAbvGr    -0.071760
MSSubClass      -0.087910
Name: SalePrice, dtype: float64

In [179]:
# ============================================
# 31. FEATURE ENGINEERING — SURFACE TOTALE
# ============================================

clean_df["TotalSF"] = (
    clean_df["TotalBsmtSF"]
    + clean_df["1stFlrSF"]
    + clean_df["2ndFlrSF"]
)

print(clean_df[[
    "TotalBsmtSF",
    "1stFlrSF",
    "2ndFlrSF",
    "TotalSF"
]].head())

   TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSF
0        856.0       856       854   2566.0
1       1262.0      1262         0   2524.0
2        920.0       920       866   2706.0
3        756.0       961       756   2473.0
4       1145.0      1145      1053   3343.0

In [180]:
# ============================================
# 32. FEATURE ENGINEERING — TOTAL BATHROOMS
# ============================================

clean_df["TotalBathrooms"] = (
    clean_df["FullBath"]
    + 0.5 * clean_df["HalfBath"]
    + clean_df["BsmtFullBath"]
    + 0.5 * clean_df["BsmtHalfBath"]
)

print(clean_df[[
    "FullBath",
    "HalfBath",
    "BsmtFullBath",
    "BsmtHalfBath",
    "TotalBathrooms"
]].head())

   FullBath  HalfBath  BsmtFullBath  BsmtHalfBath  TotalBathrooms
0         2         1           1.0           0.0             3.5
1         2         0           0.0           1.0             2.5
2         2         1           1.0           0.0             3.5
3         1         0           1.0           0.0             2.0
4         2         1           1.0           0.0             3.5

In [181]:
# ============================================
# 33. FEATURE ENGINEERING — ÂGE DU LOGEMENT
# ============================================

current_year = 2026

clean_df["HouseAge"] = (
    current_year - clean_df["YearBuilt"]
)

print(clean_df[[
    "YearBuilt",
    "HouseAge"
]].head())

   YearBuilt  HouseAge
0       2003        23
1       1976        50
2       2001        25
3       1915       111
4       2000        26

In [182]:
# ============================================
# 34. FEATURE ENGINEERING — ÂGE DEPUIS RÉNOVATION
# ============================================

clean_df["RemodAge"] = (
    current_year - clean_df["YearRemodAdd"]
)

print(clean_df[[
    "YearRemodAdd",
    "RemodAge"
]].head())

   YearRemodAdd  RemodAge
0          2003        23
1          1976        50
2          2002        24
3          1970        56
4          2000        26

In [183]:
# ============================================
# 35. VÉRIFICATION DU FEATURE ENGINEERING
# ============================================

new_features = [
    "TotalSF",
    "TotalBathrooms",
    "HouseAge",
    "RemodAge"
]

print(clean_df[new_features].describe())

           TotalSF  TotalBathrooms     HouseAge     RemodAge
count   2919.00000     2919.000000  2919.000000  2919.000000
mean    2547.48270        2.218397    54.687222    41.735526
std      805.12084        0.808840    30.291442    20.894344
min      334.00000        1.000000    16.000000    16.000000
25%     2000.00000        1.500000    25.000000    22.000000
50%     2448.00000        2.000000    53.000000    33.000000
75%     2991.50000        2.500000    72.500000    61.000000
max    11752.00000        7.000000   154.000000    76.000000

In [184]:
print(
    clean_df[new_features].isna().sum()
)

TotalSF           0
TotalBathrooms    0
HouseAge          0
RemodAge          0
dtype: int64

In [185]:
# ============================================
# 36. CORRÉLATION DES NOUVELLES VARIABLES
# ============================================

new_correlations = (
    clean_df[
        new_features + ["SalePrice"]
    ]
    .corr()["SalePrice"]
    .sort_values(ascending=False)
)

print(new_correlations)

SalePrice         1.000000
TotalSF           0.618720
TotalBathrooms    0.461525
RemodAge         -0.350032
HouseAge         -0.362066
Name: SalePrice, dtype: float64

In [186]:
clean_df["LotFrontage"].fillna(
    clean_df["LotFrontage"].median()
)

0        65.0
1        80.0
2        68.0
3        60.0
4        84.0
        ...
2914     21.0
2915     21.0
2916    160.0
2917     62.0
2918     74.0
Name: LotFrontage, Length: 2919, dtype: float64

In [187]:
clean_df["LotFrontage"] = clean_df["LotFrontage"].fillna(
    clean_df["LotFrontage"].median()
)

In [188]:
df = df.fillna(0)

In [189]:
# ============================================
# 37. CONCLUSION DE L'EDA
# ============================================

print("========== CONCLUSION DE L'EDA ==========\n")

print("1. Variable cible :")
print("- SalePrice présente une distribution asymétrique.")
print("- Quelques logements ont des prix particulièrement élevés.\n")

print("2. Surface habitable :")
print("- GrLivArea présente une relation positive avec SalePrice.")
print("- Les logements avec une grande surface ont généralement des prix plus élevés.\n")

print("3. Qualité du logement :")
print("- OverallQual montre une relation importante avec SalePrice.")
print("- Les logements de meilleure qualité ont généralement des prix plus élevés.\n")

print("4. Localisation :")
print("- Les prix varient selon Neighborhood.")
print("- La localisation constitue donc une information importante pour la prédiction.\n")

print("5. Année de construction :")
print("- YearBuilt permet d'observer une relation entre l'ancienneté du logement et son prix.\n")

print("6. Feature Engineering :")
print("- TotalSF représente une mesure globale des surfaces.")
print("- TotalBathrooms regroupe les différentes salles de bain.")
print("- HouseAge représente l'âge du logement.")
print("- RemodAge représente l'ancienneté depuis la dernière rénovation.\n")

print("Conclusion générale :")
print("- Les données contiennent plusieurs variables potentiellement importantes")
print("  pour prédire SalePrice.")
print("- Les variables numériques et catégorielles seront utilisées dans")
print("  un pipeline de prétraitement avant l'entraînement des modèles.")

========== CONCLUSION DE L'EDA ==========

1. Variable cible :
- SalePrice présente une distribution asymétrique.
- Quelques logements ont des prix particulièrement élevés.

2. Surface habitable :
- GrLivArea présente une relation positive avec SalePrice.
- Les logements avec une grande surface ont généralement des prix plus élevés.

3. Qualité du logement :
- OverallQual montre une relation importante avec SalePrice.
- Les logements de meilleure qualité ont généralement des prix plus élevés.

4. Localisation :
- Les prix varient selon Neighborhood.
- La localisation constitue donc une information importante pour la prédiction.

5. Année de construction :
- YearBuilt permet d'observer une relation entre l'ancienneté du logement et son prix.

6. Feature Engineering :
- TotalSF représente une mesure globale des surfaces.
- TotalBathrooms regroupe les différentes salles de bain.
- HouseAge représente l'âge du logement.
- RemodAge représente l'ancienneté depuis la dernière rénovation.

Conclusion générale :
- Les données contiennent plusieurs variables potentiellement importantes
  pour prédire SalePrice.
- Les variables numériques et catégorielles seront utilisées dans
  un pipeline de prétraitement avant l'entraînement des modèles.

In [190]:
# ============================================
# 38. VÉRIFICATION FINALE DES DONNÉES
# ============================================

print("Dimensions du dataset :", clean_df.shape)

Dimensions du dataset : (2919, 85)

In [191]:
print("\nNombre de colonnes :", len(clean_df.columns))
print("\nColonnes :")
print(clean_df.columns.tolist())

Nombre de colonnes : 85

Colonnes :
['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice', 'TotalSF', 'TotalBathrooms', 'HouseAge', 'RemodAge']

In [192]:
missing_final = clean_df.isnull().sum()

missing_final = missing_final[missing_final > 0].sort_values(
    ascending=False
)

print("\n========== VALEURS MANQUANTES ==========")
print(missing_final)

========== VALEURS MANQUANTES ==========
Series([], dtype: int64)

In [193]:
missing_final = clean_df.isnull().sum()

missing_final = missing_final[missing_final > 0].sort_values(
    ascending=False
)

print("\n========== VALEURS MANQUANTES ==========")
print(missing_final)

========== VALEURS MANQUANTES ==========
Series([], dtype: int64)

In [194]:
print("\n========== DOUBLONS ==========")

print(
    "Nombre de doublons :",
    clean_df.duplicated().sum()
)

========== DOUBLONS ==========
Nombre de doublons : 0

In [195]:
print("\n========== SALEPRICE ==========")

print("Valeurs manquantes :", clean_df["SalePrice"].isna().sum())
print("Minimum :", clean_df["SalePrice"].min())
print("Maximum :", clean_df["SalePrice"].max())
print("Moyenne :", clean_df["SalePrice"].mean())
print("Médiane :", clean_df["SalePrice"].median())

========== SALEPRICE ==========
Valeurs manquantes : 0
Minimum : 34900.0
Maximum : 755000.0
Moyenne : 180052.85464749733
Médiane : 176734.841494027

In [196]:
print("\n========== NOUVELLES FEATURES ==========")

new_features = [
    "TotalSF",
    "TotalBathrooms",
    "HouseAge",
    "RemodAge"
]

print(clean_df[new_features].head())
print("\nValeurs manquantes :")
print(clean_df[new_features].isna().sum())

========== NOUVELLES FEATURES ==========
   TotalSF  TotalBathrooms  HouseAge  RemodAge
0   2566.0             3.5        23        23
1   2524.0             2.5        50        50
2   2706.0             3.5        25        24
3   2473.0             2.0       111        56
4   3343.0             3.5        26        26

Valeurs manquantes :
TotalSF           0
TotalBathrooms    0
HouseAge          0
RemodAge          0
dtype: int64

In [197]:
print("\n========== TYPES DE DONNÉES ==========")

print(clean_df.dtypes.value_counts())

========== TYPES DE DONNÉES ==========
int64      28
object     23
str        20
float64    14
Name: count, dtype: int64

In [198]:
print("\nVariables numériques :", 
      len(clean_df.select_dtypes(include=["int64", "float64"]).columns))

print("Variables catégorielles :", 
      len(clean_df.select_dtypes(include=["object"]).columns))

Variables numériques : 42
Variables catégorielles : 43

C:\Users\Olaya\AppData\Local\Temp\ipykernel_10732\2120736644.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  len(clean_df.select_dtypes(include=["object"]).columns))

In [199]:
# ============================================
# 39. SÉPARATION DE LA CIBLE
# ============================================

X = clean_df.drop(columns=["SalePrice"])
y = clean_df["SalePrice"]

print("X :", X.shape)
print("y :", y.shape)

X : (2919, 84)
y : (2919,)

In [200]:
print("\nType de y :", y.dtype)
print("Nombre de valeurs manquantes dans y :", y.isna().sum())

Type de y : float64
Nombre de valeurs manquantes dans y : 0

In [201]:
# ============================================
# 40. CHECK FINAL AVANT MACHINE LEARNING
# ============================================

print("========================================")
print("     CHECK FINAL AVANT MACHINE LEARNING")
print("========================================")

print(f"\nNombre de lignes : {clean_df.shape[0]}")
print(f"Nombre de colonnes : {clean_df.shape[1]}")

print(f"\nDoublons : {clean_df.duplicated().sum()}")

print(f"\nValeurs manquantes dans SalePrice : "
      f"{clean_df['SalePrice'].isna().sum()}")

print(f"\nX : {X.shape}")
print(f"y : {y.shape}")

print("\nFeatures créées :")
for feature in new_features:
    print(f"  ✓ {feature}")

print("\n========================================")
print("EDA + FEATURE ENGINEERING TERMINÉS")
print("========================================")

========================================
     CHECK FINAL AVANT MACHINE LEARNING
========================================

Nombre de lignes : 2919
Nombre de colonnes : 85

Doublons : 0

Valeurs manquantes dans SalePrice : 0

X : (2919, 84)
y : (2919,)

Features créées :
  ✓ TotalSF
  ✓ TotalBathrooms
  ✓ HouseAge
  ✓ RemodAge

========================================
EDA + FEATURE ENGINEERING TERMINÉS
========================================